// Default WOTS Dormitory Standards and Maintenance Checklist
// Parsed from detail_list.pdf

export function getDefaultWOTSTemplate() {
  return {
    name: 'WOTS Dormitory Standards and Maintenance',
    description: 'Comprehensive dormitory inspection checklist for WOTS candidates',
    failureThreshold: 2,
    requiresApproval: true,
    areas: [
      {
        id: 'stairwells-hallways',
        name: 'Stairwells/Hallways',
        areaNumber: 2,
        locations: ['1st Floor', '2d Floor', '3d Floor'],
        demeritLimit: 4,
        order: 0,
        items: [
          { id: 'sh-1', text: 'Stairwell Clean/Free of Debris', criticalFailure: false, order: 0 },
          { id: 'sh-2', text: 'Hallway Floors Clean/Free of Debris', criticalFailure: false, order: 1 },
          { id: 'sh-3', text: 'Handrails Clean/Dust Free', criticalFailure: false, order: 2 },
          { id: 'sh-4', text: 'Doors Clean/Dust Free', criticalFailure: false, order: 3 },
          { id: 'sh-5', text: 'Lighting Operational/Reported', criticalFailure: false, order: 4 },
          { id: 'sh-6', text: 'No Unauthorized Items', criticalFailure: false, order: 5 },
          { id: 'sh-7', text: 'Carpet Clean/Free of Debris', criticalFailure: false, order: 6 },
          { id: 'sh-8', text: 'Water Fill Stations Clean/Dry', criticalFailure: false, order: 7 },
          { id: 'sh-9', text: 'Free of Safety Hazards', criticalFailure: true, order: 8 },
        ],
      },
      {
        id: 'supply-rooms',
        name: 'Supply Rooms',
        areaNumber: 3,
        locations: ['1st Floor', '2d Floor', '3d Floor'],
        demeritLimit: 4,
        order: 1,
        items: [
          { id: 'sr-1', text: 'Floor Clean/Free of Debris', criticalFailure: false, order: 0 },
          { id: 'sr-2', text: 'Shelves Clean/Dust Free', criticalFailure: false, order: 1 },
          { id: 'sr-3', text: 'Supplies Clean/Dust Free', criticalFailure: false, order: 2 },
          { id: 'sr-4', text: 'Items on Shelves Organized', criticalFailure: false, order: 3 },
          { id: 'sr-5', text: 'Window/Windowsill Clean/Dust Free', criticalFailure: false, order: 4 },
          { id: 'sr-6', text: 'Door Closed/Clean/Dust Free', criticalFailure: false, order: 5 },
          { id: 'sr-7', text: 'No Unauthorized Items', criticalFailure: false, order: 6 },
          { id: 'sr-8', text: 'Shower Clean/Dry', criticalFailure: false, order: 7 },
          { id: 'sr-9', text: 'Toilet Clean/Seat Down', criticalFailure: false, order: 8 },
          { id: 'sr-10', text: 'Free of Safety Hazards', criticalFailure: true, order: 9 },
        ],
      },
      {
        id: 'laundry-rooms',
        name: 'Laundry Rooms',
        areaNumber: 3,
        locations: ['2d Floor', '3d Floor'],
        demeritLimit: 4,
        order: 2,
        items: [
          { id: 'lr-1', text: 'Floor Clean/Free of Debris', criticalFailure: false, order: 0 },
          { id: 'lr-2', text: 'Shelves Clean/Dust Free', criticalFailure: false, order: 1 },
          { id: 'lr-3', text: 'Supplies Clean/Dust Free', criticalFailure: false, order: 2 },
          { id: 'lr-4', text: 'Items on Shelves Organized', criticalFailure: false, order: 3 },
          { id: 'lr-5', text: 'No Excess Cleaning Supplies', criticalFailure: false, order: 4 },
          { id: 'lr-6', text: 'Window/Windowsill Clean/Dust Free', criticalFailure: false, order: 5 },
          { id: 'lr-7', text: 'Curtains/Blinds Closed/Dust Free', criticalFailure: false, order: 6 },
          { id: 'lr-8', text: 'Dryers Empty/Clean/Free of Dust', criticalFailure: false, order: 7 },
          { id: 'lr-9', text: 'Lint Traps Clean/Free of Dust/Debris', criticalFailure: false, order: 8 },
          { id: 'lr-10', text: 'Washers Empty/Clean/Free of Dust', criticalFailure: false, order: 9 },
          { id: 'lr-11', text: 'Washer Lint Drawer Clean', criticalFailure: false, order: 10 },
          { id: 'lr-12', text: 'Door Clean/Dust Free', criticalFailure: false, order: 11 },
          { id: 'lr-13', text: 'Door Properly Displayed', criticalFailure: false, order: 12 },
          { id: 'lr-14', text: 'Sink/Counter Clean/Dry/Dust Free', criticalFailure: false, order: 13 },
          { id: 'lr-15', text: 'Big Bins Neatly Displayed', criticalFailure: false, order: 14 },
          { id: 'lr-16', text: 'Free of Safety Hazards', criticalFailure: true, order: 15 },
        ],
      },
      {
        id: 'classrooms',
        name: 'Classrooms',
        areaNumber: 2,
        locations: ['Barrow', 'Long', 'Brew'],
        demeritLimit: 4,
        order: 3,
        items: [
          { id: 'cr-1', text: 'Floor Clean/Free of Debris', criticalFailure: false, order: 0 },
          { id: 'cr-2', text: 'Furniture Neat/Clean', criticalFailure: false, order: 1 },
          { id: 'cr-3', text: 'Door Open/Clean/Dust Free', criticalFailure: false, order: 2 },
          { id: 'cr-4', text: 'No Unauthorized Items', criticalFailure: false, order: 3 },
          { id: 'cr-5', text: 'Lights Off', criticalFailure: false, order: 4 },
          { id: 'cr-6', text: 'Trash Bin Empty', criticalFailure: false, order: 5 },
          { id: 'cr-7', text: 'Free of Safety Hazards', criticalFailure: true, order: 6 },
        ],
      },
      {
        id: 'conference-room',
        name: 'Conference Room',
        areaNumber: 1,
        locations: [],
        demeritLimit: 4,
        order: 4,
        items: [
          { id: 'conf-1', text: 'Floor Clean/Free of Debris', criticalFailure: false, order: 0 },
          { id: 'conf-2', text: 'Tables Neat/Clean', criticalFailure: false, order: 1 },
          { id: 'conf-3', text: 'Chairs Neat/Clean', criticalFailure: false, order: 2 },
          { id: 'conf-4', text: 'Door Closed/Clean/Dust Free', criticalFailure: false, order: 3 },
          { id: 'conf-5', text: 'Window/Windowsill Clean/Dust Free', criticalFailure: false, order: 4 },
          { id: 'conf-6', text: 'Free of Safety Hazards', criticalFailure: true, order: 5 },
        ],
      },
      {
        id: 'building-exterior',
        name: 'Building Exterior',
        areaNumber: 1,
        locations: [],
        demeritLimit: 4,
        order: 5,
        items: [
          { id: 'be-1', text: 'Grounds Free of Trash/Debris', criticalFailure: false, order: 0 },
          { id: 'be-2', text: 'Entryways Free of Trash/Debris', criticalFailure: false, order: 1 },
          { id: 'be-3', text: 'Entry Ways Clean', criticalFailure: false, order: 2 },
          { id: 'be-4', text: 'Walkways Clean/Free of Debris', criticalFailure: false, order: 3 },
          { id: 'be-5', text: 'AFROTC Arena Clean/Free of Debris', criticalFailure: false, order: 4 },
        ],
      },
      {
        id: 'latrine-sink',
        name: 'Latrine/Sink Areas',
        areaNumber: 4,
        locations: ['106/07', '108/09', '109/11', '110/12', '113/16'],
        demeritLimit: 4,
        order: 6,
        items: [
          { id: 'ls-1', text: 'Floor Clean/Free of Debris', criticalFailure: false, order: 0 },
          { id: 'ls-2', text: 'Door Open/Clean/Dust Free', criticalFailure: false, order: 1 },
          { id: 'ls-3', text: 'Showers Clean/Dry', criticalFailure: false, order: 2 },
          { id: 'ls-4', text: 'Toilet Clean/Seat Down', criticalFailure: false, order: 3 },
          { id: 'ls-5', text: 'Toilet Brush/Plunger Clean', criticalFailure: false, order: 4 },
          { id: 'ls-6', text: 'Mirrors Clean/Dust/Smudge Free', criticalFailure: false, order: 5 },
          { id: 'ls-7', text: 'Sinks Clean/Dry', criticalFailure: false, order: 6 },
          { id: 'ls-8', text: 'Soap Stocked', criticalFailure: false, order: 7 },
          { id: 'ls-9', text: 'Paper Towels Stocked', criticalFailure: false, order: 8 },
          { id: 'ls-10', text: 'Toilet Paper Stocked', criticalFailure: false, order: 9 },
          { id: 'ls-11', text: 'Free of Safety Hazards', criticalFailure: true, order: 10 },
        ],
      },
      {
        id: 'bulletin-board',
        name: 'Bulletin Board',
        areaNumber: 1,
        locations: [],
        demeritLimit: 4,
        order: 7,
        items: [
          { id: 'bb-1', text: 'All Items Professional', criticalFailure: false, order: 0 },
          { id: 'bb-2', text: 'Board is Clean/Dust Free', criticalFailure: false, order: 1 },
          { id: 'bb-3', text: 'All Document Corners Fastened', criticalFailure: false, order: 2 },
          { id: 'bb-4', text: 'All Documents Current/Up to Date', criticalFailure: false, order: 3 },
        ],
      },
    ],
  }
}
